/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package emujava;

import javax.swing.JFrame;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author jBillu
 */
public class ProcessProgress extends javax.swing.JDialog {

    /**
     * Creates new form ProcessProgress
     */
    public ProcessProgress(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            int x = ( (int )dim.getWidth() - 360 ) / 2;
            int y = ( (int )dim.getHeight() - 162 ) / 2;
            this.setLocation( x, y );
        } catch( Exception except ) {
            except.printStackTrace();
        } //END try-catch BLOCK
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        ppBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Progress Status");
        setPreferredSize(new java.awt.Dimension(360, 162));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Test Case Generation process has begun. It may take several");
        jLabel1.setPreferredSize(new java.awt.Dimension(320, 20));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        jLabel2.setText("minutes to complete...");
        jLabel2.setPreferredSize(new java.awt.Dimension(320, 20));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, -1));

        titleLabel.setPreferredSize(new java.awt.Dimension(320, 20));
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));

        statusLabel.setPreferredSize(new java.awt.Dimension(320, 20));
        getContentPane().add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 105, -1, -1));

        ppBar.setPreferredSize(new java.awt.Dimension(330, 30));
        getContentPane().add(ppBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcessProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcessProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcessProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcessProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProcessProgress dialog = new ProcessProgress(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
            }
        });
    }
   
   public static ProcessProgress getProcessProgress( JFrame jFrame ) {
      if( processProgress==null ) {
         processProgress = new ProcessProgress( jFrame, false );
      } //END if STATEMENT
      return processProgress;
   } //END getProcessProgress() EMTHOD

   public static ProcessProgress getProcessProgress() {
      return processProgress;
   } //END getProcessProgress() EMTHOD

   private static ProcessProgress processProgress;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JProgressBar ppBar;
    public javax.swing.JLabel statusLabel;
    public javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
